### ISSUE TITLE
Add Stride Logo

### ISSUE THREAD

**Issue by ryanjwilke** [codeship/shipyard#123]
We need to add the [stride logo](https://www.atlassian.com/company/news/press-kit) as requested by @joshpuetz for a project he's working on.

**Comment by joshpuetz** [comment]
FYI, found several Atlassian marketing materials with logos here: https://atlassian.design/guidelines/marketing/resources/logo-files

**Comment by joshpuetz** [comment]
Related Mothership PR here: https://github.com/codeship/mothership/pull/6174

**Comment by jsouth** [comment]
Closing this issue as this is has been added to mothership, and ultimately not needed in shipyard.
