### ISSUE TITLE
Update Tracking Snippet for ProdPerfect

### ISSUE THREAD

**Issue by ryanjwilke** [codeship/shipyard#125]
Apparently, the tracking snippet we're using for our ProdPerfect demo needs to be changed to what's in this file: https://hiabe.trackinglibrary.prodperfect.com/keen-tracking.min.js

**Comment by jsouth** [comment]
@ryanjwilke - Ok will check this out and let you know if I have any questions!

**Comment by danwiding** [comment]
ah our mistake it that reference definitely works but a better version under that * subdomain is https://codeship.trackinglibrary.prodperfect.com/keen-tracking.min.js

Also the more important part is the reference to the datapipe which should be `host: 'codeship.datapipe.prodperfect.com/v1'`

For simplicity's sake I uploaded the full snippet below

[codeship-data-recorder.txt](https://github.com/codeship/shipyard/files/2151267/codeship-data-recorder.txt)

**Comment by ryanjwilke** [comment]
Closed in #129
